### ISSUE TITLE
SE 0.6 space elevator milestone seems to be broken

### ISSUE THREAD

**Issue by mgabor3141** [Wiwiweb/FactorioMilestones#12]
I crafted one and didn't get the milestone. Item id seems fine in the preset, but it might be that a different dummy item is crafted maybe.

**Comment by Wiwiweb** [comment]
![image](https://user-images.githubusercontent.com/4723472/210852635-d8fbed9a-c367-4109-b393-bb10d0121b9c.png)
Works On My Machine 😄 

Can you ctrl+f "space elevator" in your production stats?
![image](https://user-images.githubusercontent.com/4723472/210853166-c613e3ea-ac99-4686-8483-51f34c109daf.png)

**Comment by mgabor3141** [comment]
It does not show up!

![image](https://user-images.githubusercontent.com/9047995/211142431-e2f1b12b-78c8-4888-98c1-dbd65cf718b4.png)

I crafted it in a space assembling machine and I do have it:

![image](https://user-images.githubusercontent.com/9047995/211142456-95510248-2e43-4e93-8099-0580fc46626d.png)

Very strange!

**Comment by Wiwiweb** [comment]
Milestones relies on production stats so that explains why the milestone didn't trigger.

Handcrafting normally shows up in production stats too. Unfortunately I don't know what would cause the missing elevator in your stats, maybe some other mod.
