### ISSUE TITLE
Crash with K2 + 248k (+ more)

### ISSUE THREAD

**Issue by kholto** [Wiwiweb/FactorioMilestones#16]
Crash to main menu notice:
![billede](https://github.com/Wiwiweb/FactorioMilestones/assets/7372282/3055953e-d5fd-4813-ba28-39e7cce2bffe)

To reproduce: 

1. Load mods listed below (save included for sync)
2. Don't enable cheats
3. Hand craft first basic tech cards (4 copper plates and 5 wood required)
4. Attempt to open milestones

- Might only work if "Show incomplete milestones" is off
- Alternatively open milestones in the included autosave

Mod configs loaded by Milestones:
![billede](https://github.com/Wiwiweb/FactorioMilestones/assets/7372282/6db46042-ebae-4bf4-8652-1a44e91574cd)

Complete list of mods (copied from log):
 1.863 Loading mod core 0.0.0 (data.lua)
   1.904 Loading mod base 1.1.104 (data.lua)
   3.081 Loading mod belt-visualizer 1.3.5 (data.lua)
   2.089 Loading mod blueprint-shotgun 0.0.3 (data.lua)
   2.098 Loading mod EvoGUI 0.4.601 (data.lua)
   2.106 Loading mod simple-vehicle-physics 0.0.14 (data.lua)
   2.114 Loading mod VehicleSnap 1.18.5 (data.lua)
   2.123 Loading mod WireShortcuts 1.1.13 (data.lua)
   2.132 Loading mod YARM 0.10.14 (data.lua)
   2.144 Loading mod ArmouredBiters 1.1.9 (data.lua)
   2.162 Loading mod Cold_biters 1.2.1 (data.lua)
   2.188 Loading mod even-distribution 1.0.10 (data.lua)
   2.204 Loading mod Fill4Me 0.10.0 (data.lua)
   2.215 Loading mod flib 0.13.0 (data.lua)
   2.226 Loading mod FNEI 0.4.2 (data.lua)
   2.238 Loading mod helmod 0.12.23 (data.lua)
   2.253 Loading mod informatron 0.3.4 (data.lua)
   2.264 Loading mod Long_Range_Delivery_Drones 1.0.6 (data.lua)
   2.278 Loading mod MaxRateCalculator 3.4.48 (data.lua)
   2.287 Loading mod ModuleInserterSimplified 1.1.4 (data.lua)
   2.296 Loading mod queue-to-front-button 0.1.1 (data.lua)
   2.306 Loading mod redo 0.2.13 (data.lua)
   2.316 Loading mod smaller-mod-list 0.0.1 (data.lua)
   2.325 Loading mod Toxic_biters 1.1.5 (data.lua)
   2.348 Loading mod CursorEnhancements 2.1.0 (data.lua)
   2.358 Loading mod Explosive_biters 2.0.5 (data.lua)
   2.379 Loading mod FluidMustFlow 1.3.5 (data.lua)
   2.395 Loading mod Krastorio2 1.3.23 (data.lua)
   2.497 Loading mod Milestones 1.3.24 (data.lua)
   2.514 Loading mod ModuleInserterEx 6.1.2 (data.lua)
   2.530 Loading mod PipeVisualizer 2.2.0 (data.lua)
   2.545 Loading mod RealisticReactors 3.1.4 (data.lua)
   2.578 Loading mod 248k 1.0.31 (data.lua)
   2.623 Loading mod base 1.1.104 (data-updates.lua)
   2.642 Loading mod Cold_biters 1.2.1 (data-updates.lua)
   2.661 Loading mod Squeak Through 1.8.2 (data-updates.lua)
   2.681 Loading mod Krastorio2 1.3.23 (data-updates.lua)
   2.790 Loading mod RealisticReactors 3.1.4 (data-updates.lua)
   2.812 Loading mod simple-vehicle-physics 0.0.14 (data-final-fixes.lua)
   2.833 Loading mod vehicle-corpses 0.0.9 (data-final-fixes.lua)
   2.854 Loading mod WireShortcuts 1.1.13 (data-final-fixes.lua)
   2.878 Loading mod YARM 0.10.14 (data-final-fixes.lua)
   2.898 Loading mod Long_Range_Delivery_Drones 1.0.6 (data-final-fixes.lua)
   4.740 Loading mod ModuleInserterSimplified 1.1.4 (data-final-fixes.lua)
   3.780 Loading mod BottleneckLite 1.2.8 (data-final-fixes.lua)
   3.819 Loading mod FluidMustFlow 1.3.5 (data-final-fixes.lua)
   3.853 Loading mod Krastorio2 1.3.23 (data-final-fixes.lua)
   3.913 Loading mod ModuleInserterEx 6.1.2 (data-final-fixes.lua)
   3.947 Loading mod RealisticReactors 3.1.4 (data-final-fixes.lua)
   3.982 Loading mod 248k 1.0.31 (data-final-fixes.lua)
[_autosave3.zip](https://github.com/Wiwiweb/FactorioMilestones/files/14462379/_autosave3.zip)

**Comment by Wiwiweb** [comment]
Thanks for the great bug report and repro case.

Should be fixed in 1.3.25 released just now, please try it out!
