### ISSUE TITLE
zh-CN locale update

### ISSUE THREAD

**Issue by PlexPt** [Wiwiweb/FactorioMilestones#18]
Milestones.cfg
[mile.txt](https://github.com/user-attachments/files/17745531/mile.txt)

**Comment by Wiwiweb** [comment]
Locale changes are handled by a bot that pulls from Crowdin. If I merge this, your changes will be overwritten by the bot on the next update.

Please look for the milestones mod here: https://crowdin.com/project/factorio-mods-localization
